### ISSUE TITLE
small things in WebThings Gateway 1.0

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway#2688]
I just wanted to share some small things I noticed in Gateway 1.0. This is on a Pi 4 where it was updated from version 0.12.

In the logs:
```
2020-12-16 20:51:15.932 ERROR  : { Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at startPromise.Settings.get.then (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:644:1) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }
```

In the Brave browser console:

```
[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"network-settings-wifi-password" class=​"network-password" type=​"password" data-l10n-id=​"network-settings-wifi-password">​
addons:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"network-settings-wan-password" class=​"network-password" type=​"password">​
addons:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"network-settings-wlan-password" class=​"network-password" type=​"password">​
5[DOM] Input elements should have autocomplete attributes <attribute>: (More info: <URL>) 
onloadwff.js:71 [Violation] 'setTimeout' handler took 110ms
onloadwff.js:71 [Violation] 'setTimeout' handler took 391ms
onloadwff.js:71 [Violation] 'setTimeout' handler took 267ms
shaka-player.compiled.js:724 EmeEncryptionSchemePolyfill: EME not found
shaka-player.compiled.js:729 McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
```

**Comment by mrstegeman** [comment]
The first one indicates that your Pi is out of memory. Is something eating up a bunch of memory?

**Comment by flatsiedatsie** [comment]
Whoops, I was wrong. That was in the log of the Pi Zero, which only has 512 Mb of ram.

**Comment by mrstegeman** [comment]
Ok. Let me clean things up here...

**Comment by flatsiedatsie** [comment]
is this on the Pi Zero of any consequence? 

```
2020-12-16 21:49:09.467 ERROR  : Failed to renew certificate: Error: Failed to set DNS token on server: 404
    at Object.challengeCreateFn (/home/pi/mozilla-iot/gateway/build/webpack:/src/certificate-manager.js:298:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by mrstegeman** [comment]
Can you paste the contents of `/home/pi/mozilla-iot/gateway/config/default.js`?

**Comment by flatsiedatsie** [comment]
```
pi@kitchen:~ $ cat /home/pi/mozilla-iot/gateway/config/default.js
/*
 * WebThings Gateway Default Configuration.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

'use strict';

const os = require('os');
const path = require('path');
const home = os.homedir();

module.exports = {
  // Base profile directory
  profileDir: `${home}/.webthings`,

  ports: {
    // HTTPS port
    https: 4443,

    // HTTP port
    http: 8080,

    // IPC port -- changing this will likely break all add-ons
    ipc: 9500,
  },

  // Whether the gateway is behind port forwarding and should use simplified
  // port-free urls
  behindForwarding: true,

  addonManager: {
    // URLs of add-on lists to parse, in order
    listUrls: [
      'https://api.webthings.io:8443/addons',
    ],

    // Whether or not to allow installation of test-only add-ons
    testAddons: false,
  },

  database: {
    // Remove the database before opening. Only useful for testing.
    removeBeforeOpen: false,
  },

  settings: {
    defaults: {
      mdns: {
        // Whether or not to enable mDNS advertisements
        enabled: true,

        // Domain to advertise via mDNS
        domain: os.hostname().split('.')[0],
      },
    },
  },

  ssltunnel: {
    // Whether or not to enable the PageKite tunnel (if set up)
    enabled: true,

    // Endpoint of the PageKite server
    registration_endpoint: 'https://api.webthings.io:8443',

    // Base domain
    domain: 'webthings.io',

    // Command to run PageKite
    pagekite_cmd: path.normalize(path.join(process.cwd(), 'pagekite.py')),

    // Port the PageKite server is running on
    port: 443,

    // Email address to use during certificate generation
    certemail: 'noreply@webthings.io',
  },

  updates: {
    // URL of update server
    url: 'https://api.webthings.io:8443/releases',

    // Whether or not to allow prerelease updates
    allowPrerelease: false,
  },

  wifi: {
    ap: {
      // IP address to run captive portal on
      ipaddr: '192.168.2.1',

      // Base SSID to use for captive portal (suffix will include MAC address
      // components)
      ssid_base: 'WebThings Gateway',
    },
  },

  oauth: {
    // Whether or not to post the OAuth token back in the response
    postToken: false,

    // Whether or not to allow test clients
    testClients: false,
  },
};
```

**Comment by flatsiedatsie** [comment]
Noticed this in the Pi Zero log too. I think this happened when I toggled an addon to on and then back to off in quick successsion.

```
2020-12-16 21:55:03.233 INFO   : Loading add-on: internet-radio
2020-12-16 21:55:04.921 ERROR  : Failed to toggle add-on internet-radio
2020-12-16 21:55:04.976 ERROR  : TypeError: Cannot read property 'send' of undefined
    at Plugin.sendMsg (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:580:1)
    at Plugin.unload (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:737:1)
    at AddonManager.unloadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:979:1)
    at AddonManager.disableAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:615:1)
```

**Comment by flatsiedatsie** [comment]
On the Pi 4 I see a lot of this in the log:

```
2020-12-16 11:18:40.324 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:18:43.480 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:19:00.157 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:19:03.362 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:19:20.063 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:19:23.230 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:19:39.940 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:19:43.177 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:20:00.081 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:20:04.436 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:20:21.249 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:20:24.440 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:20:41.248 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:20:44.441 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:21:01.156 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:21:04.449 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:21:21.171 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:21:24.430 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:21:42.050 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:21:53.108 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:22:09.861 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:22:13.159 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:22:29.908 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:22:33.107 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:22:49.959 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:22:53.178 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:23:09.993 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:23:13.286 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:23:30.169 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:23:33.393 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:23:50.123 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:23:53.316 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:24:10.226 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:24:13.447 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:24:30.257 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:24:33.567 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:24:50.532 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:24:53.742 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:25:10.658 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:25:13.968 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:25:30.749 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:25:33.891 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:25:50.701 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:25:53.892 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:26:10.686 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:26:13.843 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:26:30.627 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:26:33.703 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:26:50.344 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:26:53.458 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:27:10.231 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:27:13.451 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:27:30.267 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:27:33.503 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:27:50.323 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:27:53.402 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:28:10.307 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:28:14.606 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:28:31.525 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:28:34.841 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:28:51.657 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:28:54.856 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:29:11.703 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:29:14.953 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:29:31.661 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:29:34.729 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:29:51.452 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:29:54.653 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:30:11.622 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:30:14.887 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:30:31.812 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:30:35.077 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:30:51.902 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:30:55.196 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:31:12.027 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:31:15.198 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:31:31.818 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:31:36.344 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:31:53.360 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:31:56.542 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:32:13.507 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:32:16.811 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:32:33.674 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:32:36.850 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:32:53.817 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:32:57.069 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:33:13.916 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:33:17.094 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:33:33.865 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:33:37.109 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:33:53.834 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:33:57.028 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:34:14.020 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:34:17.278 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:34:34.205 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:34:37.503 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:34:54.462 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:34:57.652 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:35:14.479 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:35:17.700 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:35:34.363 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:35:35.881 INFO   : zigbee-adapter: Kicking WatchDog for 3600 seconds
2020-12-16 11:35:37.534 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:35:54.446 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:35:57.590 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:36:14.602 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:36:17.854 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:36:34.625 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:36:37.976 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:36:54.786 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:36:58.031 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:37:14.875 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:37:18.105 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:37:34.985 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:37:38.338 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:37:55.169 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:37:58.327 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:38:15.293 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:38:18.504 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:38:35.057 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:38:38.204 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:38:55.584 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:39:01.781 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:39:19.923 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:39:23.686 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:39:40.388 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:39:43.744 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:40:00.554 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:40:03.906 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:40:20.672 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:40:23.897 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
2020-12-16 11:40:40.746 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-16 11:40:43.973 INFO   : wifi-setup: waitForWiFi: networks exist: [ 'ssid_was_here' ]
```

**Comment by mrstegeman** [comment]
> Noticed this in the Pi Zero log too. I think this happened when I toggled an addon to on and then back to off in quick successsion.
> 
> ```
> 2020-12-16 21:55:03.233 INFO   : Loading add-on: internet-radio
> 2020-12-16 21:55:04.921 ERROR  : Failed to toggle add-on internet-radio
> 2020-12-16 21:55:04.976 ERROR  : TypeError: Cannot read property 'send' of undefined
>     at Plugin.sendMsg (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:580:1)
>     at Plugin.unload (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:737:1)
>     at AddonManager.unloadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:979:1)
>     at AddonManager.disableAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:615:1)
> ```

This is #2497.

**Comment by mrstegeman** [comment]
Your Pi 4 doesn't seem to be behaving very well. Is it even on the network?

**Comment by mrstegeman** [comment]
I'm not sure what's going on with your Pi Zero. Can you run this from the command line and post the output?

```sh
curl -w '\n%{http_code}\n' "https://api.webthings.io:8443/dnsconfig"
```

**Comment by flatsiedatsie** [comment]
> Your Pi 4 doesn't seem to be behaving very well. Is it even on the network?

Yes it is, wifi only. It seems to work ok. I'm connected via SSH at the same time. I didn't see those messages on 0.12.

Here is the command output on the Pi Zero:

```
pi@kitchen:~ $ curl -w '\n%{http_code}\n' "https://api.webthings.io:8443/dnsconfig"
Query deserialize error: missing field `token`
400

```

**Comment by flatsiedatsie** [comment]
Here's some startup logs from another device, a Pi 3, with a pre-flashed $4 Zigbee stick. It has updated itself to Webthings 1.0 in the backgound a few days ago. This device is far from 'stock' though, so any errors could be result of additionally installed software.

```
2020-12-17 09:17:46.416 INFO   : Checking for add-on updates...
2020-12-17 09:17:47.051 INFO   : zigbee-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2020-12-17 09:17:47.669 ERROR  : Failed to parse add-on list: { FetchError: request to https://api.webthings.io:8443/addons?arch=linux-arm&version=1.0.0&node=64&python=2.7%2C3.7 failed, reason: getaddrinfo ENOTFOUND api.webthings.io api.webthings.io:8443
    at ClientRequest.<anonymous> (/home/pi/mozilla-iot/gateway/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://api.webthings.io:8443/addons?arch=linux-arm&version=1.0.0&node=64&python=2.7%2C3.7 failed, reason: getaddrinfo ENOTFOUND api.webthings.io api.webthings.io:8443',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
2020-12-17 09:17:51.969 INFO   : zigbee-adapter: Loading add-on zigbee-adapter from /home/pi/.webthings/addons/zigbee-adapter
2020-12-17 09:17:52.182 INFO   : zigbee-adapter: DEBUG config = ''
2020-12-17 09:17:53.247 ERROR  : zigbee-adapter: SerialProber: timeout: cc2531 dongle not detected on /dev/ttyACM0
2020-12-17 09:17:53.251 INFO   : zigbee-adapter: Serial ports that were found:
2020-12-17 09:17:53.623 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyAMA0
2020-12-17 09:17:53.627 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyS0
2020-12-17 09:17:53.630 INFO   : zigbee-adapter: USB Serial Device 0451:16a8 Vendor: Texas Instruments Serial: __0X00124B0018E2AB77 found @ /dev/ttyACM0
2020-12-17 09:17:53.634 ERROR  : zigbee-adapter: Failed to start add-on zigbee-adapter: No Zigbee dongle found
2020-12-17 09:20:29.885 INFO   : Tunnel name is set to: Not set.
2020-12-17 09:20:29.888 INFO   : Local mDNS Service Domain Name is: name_was_here
2020-12-17 09:20:33.363 ERROR  : Failed to get property level: getProperty: device: zb-086bd7fffe59a948 not found.
2020-12-17 09:20:33.366 ERROR  : Failed to get property on: getProperty: device: zb-086bd7fffe59a948 not found.
2020-12-17 09:20:48.670 INFO   : Tunnel name is set to: Not set.
```

**Comment by mrstegeman** [comment]
> Could it be caused by `arp -a` commands? `dmesg` looks ok. Wifi power ssaving seems to be enabled. All I see is:

Maybe.

> Here is the command output on the Pi Zero:
> 
> ```
> pi@kitchen:~ $ curl -w '\n%{http_code}\n' "https://api.webthings.io:8443/dnsconfig"
> Query deserialize error: missing field `token`
> 400
> ```

Ok, good. That's expected.

**Comment by mrstegeman** [comment]
> ```
> 2020-12-17 09:17:47.669 ERROR  : Failed to parse add-on list: { FetchError: request to https://api.webthings.io:8443/addons?arch=linux-arm&version=1.0.0&node=64&python=2.7%2C3.7 failed, reason: getaddrinfo ENOTFOUND api.webthings.io api.webthings.io:8443
>     at ClientRequest.<anonymous> (/home/pi/mozilla-iot/gateway/node_modules/node-fetch/lib/index.js:1461:11)
>     at ClientRequest.emit (events.js:198:13)
>     at TLSSocket.socketErrorListener (_http_client.js:401:9)
>     at TLSSocket.emit (events.js:198:13)
>     at emitErrorNT (internal/streams/destroy.js:91:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>   message:
>    'request to https://api.webthings.io:8443/addons?arch=linux-arm&version=1.0.0&node=64&python=2.7%2C3.7 failed, reason: getaddrinfo ENOTFOUND api.webthings.io api.webthings.io:8443',
>   type: 'system',
>   errno: 'ENOTFOUND',
>   code: 'ENOTFOUND' }
> ```

This indicates that your Pi has no internet access, as the DNS lookup for `api.webthings.io` is failing.

> ```
> 2020-12-17 09:17:51.969 INFO   : zigbee-adapter: Loading add-on zigbee-adapter from /home/pi/.webthings/addons/zigbee-adapter
> 2020-12-17 09:17:52.182 INFO   : zigbee-adapter: DEBUG config = ''
> 2020-12-17 09:17:53.247 ERROR  : zigbee-adapter: SerialProber: timeout: cc2531 dongle not detected on /dev/ttyACM0
> 2020-12-17 09:17:53.251 INFO   : zigbee-adapter: Serial ports that were found:
> 2020-12-17 09:17:53.623 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyAMA0
> 2020-12-17 09:17:53.627 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyS0
> 2020-12-17 09:17:53.630 INFO   : zigbee-adapter: USB Serial Device 0451:16a8 Vendor: Texas Instruments Serial: __0X00124B0018E2AB77 found @ /dev/ttyACM0
> 2020-12-17 09:17:53.634 ERROR  : zigbee-adapter: Failed to start add-on zigbee-adapter: No Zigbee dongle found
> ```

That's a Zigbee adapter issue, not gateway.

> ```
> 2020-12-17 09:20:33.363 ERROR  : Failed to get property level: getProperty: device: zb-086bd7fffe59a948 not found.
> 2020-12-17 09:20:33.366 ERROR  : Failed to get property on: getProperty: device: zb-086bd7fffe59a948 not found.
> ```

This is expected, given that the dongle wasn't found.

**Comment by kgiori** [comment]
@flatsiedatsie -- what is the $4 zigbee dongle you found and did it actually ever work?

**Comment by flatsiedatsie** [comment]
It did. Though the Conbee 2 supports more types of zigbee devices. e.g. the IKEA motion sensor and IKEA remote controls only works with the Conbee 2.

**Comment by flatsiedatsie** [comment]
I'm getting the same error while looking at the zigbee2mqtt adapter that I saw with the zigbee-adapter:

```
2021-01-25 23:32:56.128 INFO   : zigbee2mqtt-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2021-01-25 23:32:59.122 INFO   : zigbee2mqtt-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
```

**Comment by mrstegeman** [comment]
It’s not an error, as evidenced by the `INFO` tag. It’s expected behavior.
