### ISSUE TITLE
Intermittent test failure: basic browser tests › creates a user

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#2866]
The following browser test fails intermittently in CI.

-----
Summary of all failing tests
FAIL test/browser/load-test.js (25.22 s)
  ● basic browser tests › creates a user

    Node is either not visible or not an HTMLElement
    Error: Node is either not visible or not an HTMLElement

      at ElementHandle._clickablePoint (../node_modules/puppeteer-core/src/common/JSHandle.ts:421:13)
          at runMicrotasks (<anonymous>)
      at ElementHandle.click (../node_modules/puppeteer-core/src/common/JSHandle.ts:493:22)

**Comment by benfrancis** [comment]
I see different errors each time this test runs, but here is another one.

Summary of all failing tests
FAIL test/browser/load-test.js (26.446 s)
  ● basic browser tests › creates a user

    stale element reference: The element with reference ELEMENT-35 is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
    stale element reference: stale element reference: The element with reference ELEMENT-35 is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```

      149 |     });
      150 |     await things![0].waitForDisplayed({ timeout: DEFAULT_CLICKABLE_TIMEOUT });
    > 151 |     await things![0].click();
          |     ^
      152 |
      153 |     let link = await things![0].$('.thing-details-link');
      154 |     await link.waitForClickable({ timeout: 10000 });

      at getStaleElementError (../node_modules/devtools/build/utils.js:181:19)
      at DevToolsDriver.elementClick (../node_modules/devtools/build/commands/elementClick.js:24:48)
          at runMicrotasks (<anonymous>)
      at Element.wrappedCommand (../node_modules/devtools/build/devtoolsdriver.js:128:26)
      at Element.wrapCommandFn (../node_modules/@wdio/utils/build/shim.js:137:29)
      at Element.wrapCommandFn (../node_modules/@wdio/utils/build/shim.js:137:29)
      at Element.elementErrorHandlerCallbackFn (../node_modules/webdriverio/build/middlewares.js:44:28)
      at Element.wrapCommandFn (../node_modules/@wdio/utils/build/shim.js:137:29)
      at Element.wrapCommandFn (../node_modules/@wdio/utils/build/shim.js:137:29)
      at Element.elementErrorHandlerCallbackFn (../node_modules/webdriverio/build/middlewares.js:44:28)
      at Element.wrapCommandFn (../node_modules/@wdio/utils/build/shim.js:137:29)
      at Object.<anonymous> (../src/test/browser/load-test.ts:151:5)
```

**Comment by benfrancis** [comment]
Test disabled in https://github.com/WebThingsIO/gateway/pull/3100

#3007 tracks re-enabling.
