### ISSUE TITLE
Fix or disable intermittently failing browser tests

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#3007]
On almost every PR at least one of the test runs in CI fails on some intermittently failing browser tests. This makes it look like the build is always broken, but it's almost certainly the tests that are broken.

We need to fix these tests, but may need to disable them in the meantime.

```
2022-11-12T12:27:46.4970418Z Summary of all failing tests
2022-11-12T12:27:46.4971210Z FAIL test/browser/things-view/thing-test.js (138.944 s)
2022-11-12T12:27:46.4972082Z   ● Thing › should render an unknown thing and be able to change properties
2022-11-12T12:27:46.4972411Z 
2022-11-12T12:27:46.4972715Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.4973239Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.4973545Z 
2022-11-12T12:27:46.4973878Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.4974298Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.4974822Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.4975150Z 
2022-11-12T12:27:46.4975548Z   ● Thing › should render an unknown thing and be able to change properties
2022-11-12T12:27:46.4975829Z 
2022-11-12T12:27:46.4976453Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.4976829Z 
2022-11-12T12:27:46.4977163Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.4977451Z 
2022-11-12T12:27:46.4977790Z   ● Thing › should render a thing with spaced property names
2022-11-12T12:27:46.4978048Z 
2022-11-12T12:27:46.4978462Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.4979025Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.4979443Z 
2022-11-12T12:27:46.4979876Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.4980302Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.4980812Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.4981142Z 
2022-11-12T12:27:46.4981504Z   ● Thing › should render a thing with spaced property names
2022-11-12T12:27:46.4981761Z 
2022-11-12T12:27:46.4982366Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.4982758Z 
2022-11-12T12:27:46.4983064Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.4983363Z 
2022-11-12T12:27:46.4983735Z   ● Thing › should render an onOffLight and be able to change properties
2022-11-12T12:27:46.4984008Z 
2022-11-12T12:27:46.4984303Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.4984897Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.4985300Z 
2022-11-12T12:27:46.4985811Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.4986342Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.4986883Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.4987212Z 
2022-11-12T12:27:46.4987601Z   ● Thing › should render an onOffLight and be able to change properties
2022-11-12T12:27:46.4987877Z 
2022-11-12T12:27:46.4988470Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.4988835Z 
2022-11-12T12:27:46.4989152Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.4989437Z 
2022-11-12T12:27:46.4989802Z   ● Thing › should render an onOffSwitch and be able to change properties
2022-11-12T12:27:46.4990092Z 
2022-11-12T12:27:46.4990373Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.4990890Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.4991171Z 
2022-11-12T12:27:46.4991615Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.4992058Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.4992574Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.4992905Z 
2022-11-12T12:27:46.4993287Z   ● Thing › should render an onOffSwitch and be able to change properties
2022-11-12T12:27:46.4993562Z 
2022-11-12T12:27:46.4994161Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.4994535Z 
2022-11-12T12:27:46.4994854Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.4995136Z 
2022-11-12T12:27:46.4995517Z   ● Thing › should render a dimmableLight and be able to change properties
2022-11-12T12:27:46.4995794Z 
2022-11-12T12:27:46.4996075Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.4996591Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.4996875Z 
2022-11-12T12:27:46.4997197Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.4997708Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.4998230Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.4998560Z 
2022-11-12T12:27:46.4998940Z   ● Thing › should render a dimmableLight and be able to change properties
2022-11-12T12:27:46.4999216Z 
2022-11-12T12:27:46.4999806Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.5000178Z 
2022-11-12T12:27:46.5000498Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.5000781Z 
2022-11-12T12:27:46.5001166Z   ● Thing › should render an onOffColorLight and be able to change properties
2022-11-12T12:27:46.5001450Z 
2022-11-12T12:27:46.5001742Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5002263Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5002543Z 
2022-11-12T12:27:46.5002882Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5003297Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5003813Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5004128Z 
2022-11-12T12:27:46.5004515Z   ● Thing › should render an onOffColorLight and be able to change properties
2022-11-12T12:27:46.5004795Z 
2022-11-12T12:27:46.5005407Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.5005780Z 
2022-11-12T12:27:46.5006095Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.5006384Z 
2022-11-12T12:27:46.5006777Z   ● Thing › should render a dimmableColorLight and be able to change properties
2022-11-12T12:27:46.5007066Z 
2022-11-12T12:27:46.5007361Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5007874Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5008155Z 
2022-11-12T12:27:46.5008476Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5008908Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5009480Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5009831Z 
2022-11-12T12:27:46.5010219Z   ● Thing › should render a dimmableColorLight and be able to change properties
2022-11-12T12:27:46.5010511Z 
2022-11-12T12:27:46.5011108Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.5011485Z 
2022-11-12T12:27:46.5011801Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.5012085Z 
2022-11-12T12:27:46.5012467Z   ● Thing › should render a multiLevelSwitch and be able to change properties
2022-11-12T12:27:46.5012751Z 
2022-11-12T12:27:46.5013044Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5013646Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5013918Z 
2022-11-12T12:27:46.5014242Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5014672Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5015194Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5015602Z 
2022-11-12T12:27:46.5015995Z   ● Thing › should render a multiLevelSwitch and be able to change properties
2022-11-12T12:27:46.5016275Z 
2022-11-12T12:27:46.5016873Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.5017245Z 
2022-11-12T12:27:46.5017576Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.5017862Z 
2022-11-12T12:27:46.5018216Z   ● Thing › should render a smartPlug and be able to change properties
2022-11-12T12:27:46.5018485Z 
2022-11-12T12:27:46.5018781Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5019410Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5019701Z 
2022-11-12T12:27:46.5020026Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5020463Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5020977Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5022476Z 
2022-11-12T12:27:46.5022839Z   ● Thing › should render a smartPlug and be able to change properties
2022-11-12T12:27:46.5023039Z 
2022-11-12T12:27:46.5023579Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.5023875Z 
2022-11-12T12:27:46.5024121Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.5024332Z 
2022-11-12T12:27:46.5024632Z   ● Thing › should render a binarySensor and be able to change properties
2022-11-12T12:27:46.5024831Z 
2022-11-12T12:27:46.5025051Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5025485Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5025702Z 
2022-11-12T12:27:46.5025998Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5026344Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5026785Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5027045Z 
2022-11-12T12:27:46.5027344Z   ● Thing › should render a binarySensor and be able to change properties
2022-11-12T12:27:46.5027544Z 
2022-11-12T12:27:46.5028170Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.5028474Z 
2022-11-12T12:27:46.5028711Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.5028929Z 
2022-11-12T12:27:46.5029242Z   ● Thing › should render a multiLevelSensor and be able to change properties
2022-11-12T12:27:46.5029453Z 
2022-11-12T12:27:46.5029676Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5030109Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5030321Z 
2022-11-12T12:27:46.5030574Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5030914Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5031351Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5031607Z 
2022-11-12T12:27:46.5031923Z   ● Thing › should render a multiLevelSensor and be able to change properties
2022-11-12T12:27:46.5032130Z 
2022-11-12T12:27:46.5032650Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.5033009Z 
2022-11-12T12:27:46.5033257Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.5033475Z 
2022-11-12T12:27:46.5033780Z   ● Thing › should render a humidity sensor and be able to change properties
2022-11-12T12:27:46.5033979Z 
2022-11-12T12:27:46.5034200Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5034637Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5034848Z 
2022-11-12T12:27:46.5035094Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5035450Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5035888Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5036144Z 
2022-11-12T12:27:46.5036449Z   ● Thing › should render a humidity sensor and be able to change properties
2022-11-12T12:27:46.5036655Z 
2022-11-12T12:27:46.5037164Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.5037457Z 
2022-11-12T12:27:46.5037701Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.5037914Z 
2022-11-12T12:27:46.5038212Z   ● Thing › Assets based things › should render camera image and show image
2022-11-12T12:27:46.5038411Z 
2022-11-12T12:27:46.5038632Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5039070Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5039266Z 
2022-11-12T12:27:46.5039517Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5039872Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5040316Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5040570Z 
2022-11-12T12:27:46.5040865Z   ● Thing › Assets based things › should render camera image and show image
2022-11-12T12:27:46.5041064Z 
2022-11-12T12:27:46.5041222Z     element (".thing") still not existing after 30000ms
2022-11-12T12:27:46.5041393Z 
2022-11-12T12:27:46.5041638Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:66:23)
2022-11-12T12:27:46.5041854Z 
2022-11-12T12:27:46.5042151Z   ● Thing › Assets based things › should render video camera and show video
2022-11-12T12:27:46.5042348Z 
2022-11-12T12:27:46.5042627Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5043055Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5043267Z 
2022-11-12T12:27:46.5043523Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5043880Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5044316Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5044571Z 
2022-11-12T12:27:46.5044859Z   ● Thing › Assets based things › should render video camera and show video
2022-11-12T12:27:46.5045059Z 
2022-11-12T12:27:46.5045229Z     element (".thing") still not existing after 30000ms
2022-11-12T12:27:46.5045396Z 
2022-11-12T12:27:46.5045641Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:66:23)
2022-11-12T12:27:46.5045860Z 
2022-11-12T12:27:46.5047299Z FAIL test/browser/load-test.js (10.102 s)
2022-11-12T12:27:46.5047686Z   ● basic browser tests › creates a user
2022-11-12T12:27:46.5047830Z 
2022-11-12T12:27:46.5048055Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5048576Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5048790Z 
2022-11-12T12:27:46.5049043Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5049404Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5049828Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5050085Z 
2022-11-12T12:27:46.5050392Z FAIL test/browser/settings-view/addon-test.js (20.596 s)
2022-11-12T12:27:46.5050857Z   ● Addon › should be able to install the virtual-things-adapter
2022-11-12T12:27:46.5051053Z 
2022-11-12T12:27:46.5051281Z     val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5051705Z     TypeError: val.split(...).flatMap(...) is not a function or its return value is not iterable
2022-11-12T12:27:46.5051917Z 
2022-11-12T12:27:46.5052168Z       at typeInput.reduce (../node_modules/devtools/build/commands/elementSendKeys.js:38:33)
2022-11-12T12:27:46.5052524Z           at Array.reduce (<anonymous>)
2022-11-12T12:27:46.5052960Z       at DevToolsDriver.elementSendKeys (../node_modules/devtools/build/commands/elementSendKeys.js:36:31)
2022-11-12T12:27:46.5053205Z 
2022-11-12T12:27:46.5053486Z   ● Addon › should be able to install the virtual-things-adapter
2022-11-12T12:27:46.5053680Z 
2022-11-12T12:27:46.5054208Z     waitUntil condition failed with the following reason: Can't call getCSSProperty on element with selector "#menu-scrim.hidden" because element wasn't found
2022-11-12T12:27:46.5054506Z 
2022-11-12T12:27:46.5054754Z       at timer.catch (../node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15)
2022-11-12T12:27:46.5054969Z 
2022-11-12T12:27:46.5054976Z 
2022-11-12T12:27:46.5055154Z Test Suites: 3 failed, 32 passed, 35 total
2022-11-12T12:27:46.5055511Z Tests:       16 failed, 1 skipped, 355 passed, 372 total
2022-11-12T12:27:46.5055773Z Snapshots:   0 total
2022-11-12T12:27:46.5056005Z Time:        352.07 s
2022-11-12T12:27:46.5056232Z Ran all test suites.
2022-11-12T12:27:46.5056361Z 
2022-11-12T12:27:46.5056649Z Jest has detected the following 5 open handles potentially keeping Jest from exiting:
2022-11-12T12:27:46.5056860Z 
2022-11-12T12:27:46.5056989Z   ●  DNSCHANNEL
2022-11-12T12:27:46.5057116Z 
2022-11-12T12:27:46.5057201Z        7 |  */
2022-11-12T12:27:46.5057387Z        8 |
2022-11-12T12:27:46.5057704Z     >  9 | import * as acme from 'acme-client';
2022-11-12T12:27:46.5057933Z          | ^
2022-11-12T12:27:46.5058234Z       10 | import config from 'config';
2022-11-12T12:27:46.5058580Z       11 | import fetch from 'node-fetch';
2022-11-12T12:27:46.5058952Z       12 | import fs from 'fs';
2022-11-12T12:27:46.5059098Z 
2022-11-12T12:27:46.5059630Z       at Runtime._requireCoreModule (../node_modules/jest-runtime/build/index.js:1380:12)
2022-11-12T12:27:46.5060151Z       at Object.<anonymous> (../node_modules/acme-client/src/util.js:6:34)
2022-11-12T12:27:46.5060628Z       at Object.<anonymous> (../node_modules/acme-client/src/http.js:8:14)
2022-11-12T12:27:46.5061116Z       at Object.<anonymous> (../node_modules/acme-client/src/client.js:10:20)
2022-11-12T12:27:46.5061601Z       at Object.<anonymous> (../node_modules/acme-client/src/index.js:5:18)
2022-11-12T12:27:46.5062061Z       at Object.<anonymous> (../src/certificate-manager.ts:9:1)
2022-11-12T12:27:46.5062490Z       at Object.<anonymous> (../src/tunnel-service.ts:22:1)
2022-11-12T12:27:46.5062868Z       at Object.<anonymous> (../src/controllers/root_controller.ts:13:1)
2022-11-12T12:27:46.5063214Z       at Object.<anonymous> (../src/router.ts:35:1)
2022-11-12T12:27:46.5063378Z 
2022-11-12T12:27:46.5063388Z 
2022-11-12T12:27:46.5063508Z   ●  Timeout
2022-11-12T12:27:46.5063616Z 
2022-11-12T12:27:46.5063929Z       22 |   const loginRoot = path.join(Constants.BUILD_STATIC_PATH, 'login');
2022-11-12T12:27:46.5064201Z       23 |
2022-11-12T12:27:46.5064445Z     > 24 |   const limiter = rateLimit({
2022-11-12T12:27:46.5064798Z          |                   ^
2022-11-12T12:27:46.5065067Z       25 |     windowMs: 15 * 60 * 1000, // 15 minutes
2022-11-12T12:27:46.5065375Z       26 |     max: 10, // 10 failed requests per windowMs
2022-11-12T12:27:46.5065674Z       27 |     skipSuccessfulRequests: true,
2022-11-12T12:27:46.5065839Z 
2022-11-12T12:27:46.5066184Z       at new MemoryStore (../node_modules/express-rate-limit/lib/memory-store.js:41:20)
2022-11-12T12:27:46.5079022Z       at RateLimit (../node_modules/express-rate-limit/lib/express-rate-limit.js:41:36)
2022-11-12T12:27:46.5079517Z       at build (../src/controllers/login_controller.ts:24:19)
2022-11-12T12:27:46.5079859Z       at Router.configure (../src/router.ts:154:57)
2022-11-12T12:27:46.5080189Z       at createGatewayApp (../src/app.ts:303:10)
2022-11-12T12:27:46.5080509Z       at Object.<anonymous> (../src/app.ts:66:38)
2022-11-12T12:27:46.5080825Z       at Object.<anonymous> (../src/test/common.ts:43:1)
2022-11-12T12:27:46.5081011Z 
2022-11-12T12:27:46.5081019Z 
2022-11-12T12:27:46.5081239Z   ●  ZLIB
2022-11-12T12:27:46.5081358Z 
2022-11-12T12:27:46.5081632Z       1 | import { remote, RemoteOptions } from 'webdriverio';
2022-11-12T12:27:46.5082250Z     > 2 | import * as selenium from 'selenium-standalone';
2022-11-12T12:27:46.5082621Z         | ^
2022-11-12T12:27:46.5082990Z       3 | import { server } from '../common';
2022-11-12T12:27:46.5083429Z       4 | import { ChildProcess } from 'child_process';
2022-11-12T12:27:46.5083808Z       5 | import { AddressInfo } from 'net';
2022-11-12T12:27:46.5083953Z 
2022-11-12T12:27:46.5084312Z       at Object.<anonymous> (../node_modules/selenium-standalone/lib/install-utils.js:7:32)
2022-11-12T12:27:46.5084870Z       at Object.<anonymous> (../node_modules/selenium-standalone/lib/install.js:25:5)
2022-11-12T12:27:46.5085389Z       at Object.<anonymous> (../node_modules/selenium-standalone/index.js:4:12)
2022-11-12T12:27:46.5085865Z       at Object.<anonymous> (../src/test/browser/browser-common.ts:2:1)
2022-11-12T12:27:46.5086369Z       at Object.<anonymous> (../src/test/browser/things-view/thing-test.ts:1:1)
2022-11-12T12:27:46.5086573Z 
2022-11-12T12:27:46.5086581Z 
2022-11-12T12:27:46.5086801Z   ●  ZLIB
2022-11-12T12:27:46.5086922Z 
2022-11-12T12:27:46.5087262Z       1 | import { remote, RemoteOptions } from 'webdriverio';
2022-11-12T12:27:46.5087764Z     > 2 | import * as selenium from 'selenium-standalone';
2022-11-12T12:27:46.5088016Z         | ^
2022-11-12T12:27:46.5088339Z       3 | import { server } from '../common';
2022-11-12T12:27:46.5088726Z       4 | import { ChildProcess } from 'child_process';
2022-11-12T12:27:46.5089085Z       5 | import { AddressInfo } from 'net';
2022-11-12T12:27:46.5089374Z 
2022-11-12T12:27:46.5089735Z       at Object.<anonymous> (../node_modules/selenium-standalone/lib/install-utils.js:7:32)
2022-11-12T12:27:46.5090287Z       at Object.<anonymous> (../node_modules/selenium-standalone/lib/install.js:25:5)
2022-11-12T12:27:46.5090792Z       at Object.<anonymous> (../node_modules/selenium-standalone/index.js:4:12)
2022-11-12T12:27:46.5091288Z       at Object.<anonymous> (../src/test/browser/browser-common.ts:2:1)
2022-11-12T12:27:46.5091749Z       at Object.<anonymous> (../src/test/browser/load-test.ts:3:1)
2022-11-12T12:27:46.5091934Z 
2022-11-12T12:27:46.5091943Z 
2022-11-12T12:27:46.5092060Z   ●  ZLIB
2022-11-12T12:27:46.5092175Z 
2022-11-12T12:27:46.5092760Z       1 | import { remote, RemoteOptions } from 'webdriverio';
2022-11-12T12:27:46.5093232Z     > 2 | import * as selenium from 'selenium-standalone';
2022-11-12T12:27:46.5093483Z         | ^
2022-11-12T12:27:46.5093803Z       3 | import { server } from '../common';
2022-11-12T12:27:46.5094183Z       4 | import { ChildProcess } from 'child_process';
2022-11-12T12:27:46.5094561Z       5 | import { AddressInfo } from 'net';
2022-11-12T12:27:46.5094721Z 
2022-11-12T12:27:46.5095074Z       at Object.<anonymous> (../node_modules/selenium-standalone/lib/install-utils.js:7:32)
2022-11-12T12:27:46.5095715Z       at Object.<anonymous> (../node_modules/selenium-standalone/lib/install.js:25:5)
2022-11-12T12:27:46.5096237Z       at Object.<anonymous> (../node_modules/selenium-standalone/index.js:4:12)
2022-11-12T12:27:46.5096728Z       at Object.<anonymous> (../src/test/browser/browser-common.ts:2:1)
2022-11-12T12:27:46.5097228Z       at Object.<anonymous> (../src/test/browser/settings-view/addon-test.ts:1:1)
2022-11-12T12:27:46.5097434Z 
2022-11-12T12:27:46.6220454Z npm ERR! code ELIFECYCLE
2022-11-12T12:27:46.6220778Z npm ERR! errno 1
2022-11-12T12:27:46.6221746Z npm ERR! webthings-gateway@1.1.0 jest: `./build/test/prepare-tests.sh && NODE_TLS_REJECT_UNAUTHORIZED=0 jest --runInBand --coverage --detectOpenHandles`
2022-11-12T12:27:46.6222190Z npm ERR! Exit status 1
2022-11-12T12:27:46.6222406Z npm ERR! 
2022-11-12T12:27:46.6222817Z npm ERR! Failed at the webthings-gateway@1.1.0 jest script.
2022-11-12T12:27:46.6223319Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-11-12T12:27:46.6253148Z 
2022-11-12T12:27:46.6254406Z npm ERR! A complete log of this run can be found in:
2022-11-12T12:27:46.6261184Z npm ERR!     /home/runner/.npm/_logs/2022-11-12T12_27_46_620Z-debug.log
2022-11-12T12:27:46.6379664Z ##[error]Process completed with exit code 1.
2022-11-12T12:27:46.6436087Z Post job cleanup.
2022-11-12T12:27:46.7655930Z [command]/usr/bin/git version
2022-11-12T12:27:46.7710770Z git version 2.38.1
2022-11-12T12:27:46.7756045Z Temporarily overriding HOME='/home/runner/work/_temp/4400820a-bb5d-43f5-9e75-9380f901e371' before making global git config changes
2022-11-12T12:27:46.7758603Z Adding repository directory to the temporary git global config as a safe directory
2022-11-12T12:27:46.7764919Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/gateway/gateway
2022-11-12T12:27:46.7808286Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-11-12T12:27:46.7845710Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-11-12T12:27:46.8081078Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-11-12T12:27:46.8100399Z http.https://github.com/.extraheader
2022-11-12T12:27:46.8117048Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-11-12T12:27:46.8145074Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-11-12T12:27:46.8622616Z Cleaning up orphan processes
```

**Comment by benfrancis** [comment]
I propose disabling all the browser tests in #3100, and keeping this issue open until they can be fixed.
